#!/usr/bin/with-contenv bash
# shellcheck shell=bash
# Based on the simple config init script from [duckdns image](https://github.com/linuxserver/docker-duckdns/blob/master/root/etc/s6-overlay/s6-rc.d/init-duckdns/run)

set -x

user=abc
group=abc
lsiown -R "$user":"$group" "$EMULATOR_PATH" "$CONFIG_PATH"

mbbsemu="$EMULATOR_PATH"/MBBSEmu
chmod a+x "$mbbsemu"
