#!/usr/bin/with-contenv bash
# Based on the simple config init script from [duckdns image](https://github.com/linuxserver/docker-duckdns/blob/master/root/etc/cont-init.d/40-config)

mbbsemu="$EMULATOR_PATH"/MBBSEmu

user=abc
group=$user

chown -R $user:$group \
	"$EMULATOR_PATH" \
	"$CONFIG_PATH"

chmod a+x "$mbbsemu"

exec s6-setuidgid abc \
	"$mbbsemu" \
    -S "$CONFIG_PATH"/appsettings.json \
	-C "$CONFIG_PATH"/modules.json
