#!/usr/bin/with-contenv bash
# Based on the simple config init script from [duckdns image](https://github.com/linuxserver/docker-duckdns/blob/master/root/etc/cont-init.d/40-config)

set +x

app=/app
config=/config
mbbsemu="$app"/MBBSEmu

user=abc
group=$user

chown -R $user:$group \
	"$app" \
	"$config"

chmod a+x "$mbbsemu"

exec s6-setuidgid abc \
	"$mbbsemu" \
    -S "$config"/appsettings.json \
	-C "$config"/modules.json
